config/routes.rb
NotSuckCms::Application.routes.draw do
  resources :resources
  root :to => 'resources#index'
  get 'styleguide'  => 'styleguide#show'

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :path, :title, :content

  validates :path, uniqueness: true, presence: true
  validates :title, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_filter :find_resource_by_id, only: [:show, :edit, :update, :destroy]

  before_filter :load_navbar_resources

  def index
  end

  def show
  end

  def new
    @resource = Resource.new
  end

  def edit
  end

  def create
    @resource = Resource.new(params[:resource])
    if @resource.save
      redirect_to resources_path, notice: 'Resource successfully created'
    else
      render :new
    end
  end

  def update
    if @resource.update_attributes (params[:resource])
      redirect_to @resource, notice: 'Resource successfully updated'
    else
      render :edit
    end
  end

  def destroy
    if @resource.delete
      redirect_to resources_path, notice: 'Resource successfully deleted'
    else
      render :edit
    end
  end

  private
  def find_resource_by_id
    @resource = Resource.find(params[:id])
  end

  def load_navbar_resources
    @resources = Resource.all
  end
end

app/controllers/styleguide_controller.rb
class StyleguideController < ApplicationController

   before_filter :load_navbar_resources

  def show
  end

  def index
  end

  def edit
  end

  def load_navbar_resources
    @resources = [Resource.new(path:'/nomnom', title:'Nomage', content:'Yes it is!')]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/styleguide_helper.rb
module StyleguideHelper
end

app/views/layouts/_flash.html.haml
- if notice.present?
  .flash.notice
    %p
      = notice
- if alert.present?
  .flash.error
    %p
      = alert

app/views/layouts/_navlinks.html.haml
%ul
  // id added to support feature test steps. Don't mess with it
  // unless you fix the steps that call out "Add Idea" in the scenarios
  = button_to "Add Idea      +", new_resource_path, method: 'get', id: 'Add Idea'
  - @resources.each do |resource|
    %li
      = link_to resource.title, url_for(resource)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotSuckCms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      The Thinkery
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/flash'
    %header
      %img{src:"/assets/thinkerylogo_glow.png", id:"thinkery_logo_glow"}
      %h1#main_title
        The Thinkery
      #decorative_bar
      = link_to(image_tag('thinkerylogo.png', id:"thinkery_logo"), resources_path, id:"home_link")
      #slogan
        "The best thoughts on the web!"
    //
    %nav.menu
      = render 'layouts/navlinks'
    #main_content.content
      = yield

app/views/layouts/styleguide.html.haml
!!!
%html
  %head
    %title
      The Thinkery
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/resources/_form.html.haml
= form_for @resource do |f|
  = f.error_messages

  .field
    =f.label :path
    =f.text_field :path

  .field
    = f.label :title, 'Title of Idea:'
    %br
    = f.text_field :title, placeholder:'Title', class: 'title'

  .field
    = f.label :content, 'Content of Idea:'
    %br
    = f.text_area :content, cols: 80, placeholder: 'Put your ideas in this box!', class: 'description'

  .actions
    = f.submit

app/views/resources/edit.html.haml
= render 'form'
= button_to('Delete', @resource, method: :delete, confirm: 'REALLY???? You want to expunge this timeless concept forever?')

app/views/resources/index.html.erb
<ul>
<%- @resources.each do |resource| %>
  <li><%= resource.path %></li>
<%- end %>
</ul>

app/views/resources/index.html.haml
//No content at this time

app/views/resources/new.html.haml
= render 'form'

app/views/resources/show.html.haml
%h2
  = @resource.title
.path_holder
  index path:
  = @resource.path
.content_text
  = @resource.content
.link_holder
  = link_to 'Edit', edit_resource_path(@resource)

app/views/styleguide/show.html.haml
%html
  %head
    %title The Thinkery Style Guide!
  %body
    #styleguide_content
      %h1.pagetitle THE THINKERY STYLE GUIDE!

      #button.content
        %h2.title BUTTON STYLE
        %button
          ADD IDEA &nbsp; &nbsp; &nbsp; &nbsp;+
        %button{:class => "submit"}
          SUBMIT

      #menu.content.menu
        %h2.title MENU STYLE
        %ul
          %li
            %a{:href => "#"}
              Manichaeism
          %li
            %a{:href => "#"}
              Perpetual Motion
          %li
            %a{:href => "#"}
              Cats
          %li
            %a{:href => "#"}
              Tacos


      #forms.content
        %h2.title FORM STYLE
        %form
          %legend TITLE OF IDEA:
          %input.title{:type => "text",
                 :name => "Title",
                 :placeholder => "Title"}
          %legend DESCRIPTION OF IDEA:
          %textarea.description{:type => "text",
                 :name => "Description",
                 :placeholder => "Put your ideas in this box!"}

      #fonts.content
        %h2.title FONTS AND PARAGRAPH STYLE
        %hgroup
          %h1 h1: THE THINKERY
          %h2 h2: THE THINKERY
          %h3 h3: THE THINKERY
          &nbsp;
          %h4 h4: THE THINKERY
          %h5 h5: THE THINKERY
          %h6 h6: THE THINKERY
        %p
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et
          tincidunt elit. Quisque nunc lectus, ullamcorper posuere adipiscing
          vitae, commodo quis ante. Nam blandit dignissim mattis. Nulla a
          enim nisl, eget egestas sem. Nullam sed metus ut lorem dapibus
          seollicitudin.

      #links.content
        %h2.title EDIT LINK STYLE
        #controls
          %a{:href =>"#"}
            EDIT
          %a{:href => "#"}
            DELETE